# 1. Examples on classes and inheritance in Python

In [1]:

class Person:
    def __init__(self, firstname, lastname):
        self.firstname = firstname
        self.lastname = lastname
    
    def full_name(self):
        return f"{self.firstname} {self.lastname}"

class Student(Person):
    def __init__(self, firstname, lastname, subject):
        super().__init__(firstname, lastname)
        self.subject = subject
    
    def printNameSubject(self):
        print(f"{self.full_name()}, {self.subject}")

class Teacher(Person):
    def __init__(self, firstname, lastname, course):
        super().__init__(firstname, lastname)
        self.course = course
    
    def printNameCourse(self):
        print(f"{self.full_name()}, teaches {self.course}")

# Example usage
me = Student('Benedikt', 'Daurer', 'physics')
me.printNameSubject()

teacher = Teacher('John', 'Smith', 'Python programming')
teacher.printNameCourse()


Benedikt Daurer, physics
John Smith, teaches Python programming


# 2. Numpy exercises

In [2]:

import numpy as np

# a
a = np.zeros(10)
a[4] = 1
print("a:", a)

# b
b = np.arange(10, 50)
print("b:", b)

# c
c = b[::-1]
print("c (reversed b):", c)

# d
d = np.arange(9).reshape(3, 3)
print("d:", d)

# e
e = np.nonzero([1, 2, 0, 0, 4, 0])
print("e (indices of non-zero elements):", e)

# f
f = np.random.rand(30)
mean_f = f.mean()
print("f (mean):", mean_f)

# g
g = np.ones((5,5))
g[1:-1,1:-1] = 0
print("g (border 1, inside 0):", g)

# h
h = np.zeros((8,8),dtype=int)
h[1::2,::2] = 1
h[::2,1::2] = 1
print("h (checkerboard):", h)

# i
i = np.tile([[0,1],[1,0]],(4,4))
print("i (checkerboard using tile):", i)

# j
Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print("j (negated elements):", Z)

# k
k = np.random.random(10)
k.sort()
print("k (sorted random vector):", k)

# l
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.array_equal(A, B)
print("l (are A and B equal?):", equal)

# m
Z = np.arange(10, dtype=np.int32)
Z **= 2
print("m (squared in-place):", Z)

# n
A = np.arange(9).reshape(3,3)
B = A + 1
C = np.dot(A,B)
D = np.diag(C)
print("n (diagonal of dot product):", D)


a: [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
b: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
c (reversed b): [49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
d: [[0 1 2]
 [3 4 5]
 [6 7 8]]
e (indices of non-zero elements): (array([0, 1, 4], dtype=int64),)
f (mean): 0.492448130592414
g (border 1, inside 0): [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
h (checkerboard): [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
i (checkerboard using tile): [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
j (negated elements): [ 0  1  2  3 -4 -5 -6 -7  8  9 10]
k (sorted random vector): [0.13159565 0.19608021 

# 3. Speed optimization using Numpy

In [3]:

import numpy as np
import time

size = 500
A = np.random.rand(size, size)
B = np.random.rand(size, size)

start = time.time()
C = np.dot(A, B)
end = time.time()
print("Time taken for matrix multiplication with numpy:", end - start, "seconds")


Time taken for matrix multiplication with numpy: 0.10028433799743652 seconds


# 4. MPI parallelization

In [10]:


# Save this as mpi_ranks.py
from mpi4py import MPI

comm = MPI.COMM_WORLD
rank = comm.Get_rank()

print(f"Hello from rank {rank}")


Hello from rank 0


In [11]:

# Save this as mpi_sum.py
from mpi4py import MPI

comm = MPI.COMM_WORLD
rank = comm.Get_rank()

data = rank
total = comm.reduce(data, op=MPI.SUM, root=0)

if rank == 0:
    print(f"The sum of all ranks is {total}")


The sum of all ranks is 0


# 5. GPU Computing (Colab required)


Run this section in Google Colab after enabling GPU:

```python
!nvidia-smi

import numpy as np
import cupy as cp

sizes = [128, 256, 512, 1024, 2048]
for size in sizes:
    np_array = np.random.rand(size, size)
    cp_array = cp.random.rand(size, size)
    print(f"Size: {size}x{size}")
    %timeit np.fft.fft2(np_array)
    %timeit cp.fft.fft2(cp_array)

# Now test with dtype float32
for size in sizes:
    np_array = np.random.rand(size, size).astype(np.float32)
    cp_array = cp.random.rand(size, size).astype(cp.float32)
    print(f"Size (float32): {size}x{size}")
    %timeit np.fft.fft2(np_array)
    %timeit cp.fft.fft2(cp_array)
```
